server:
  port: 8081
person:
  name: yaojikai
  #  age: 18
  happy: false
  list: ["yaojikai","shimengyu"]
  map: {"k1":"v1","k2":"v2"}
  set: ["yaojikai","shimengyu","shimengyu"]
  dog:
    name: wangcia
    age: 3
spring:
  profiles:
    active: test