#springboot加载配置文件，加载顺yml→yaml→properties，如果配置信息有重复，后加载的会覆盖掉先加载的

# 普通数据的配置
name: yaojikai

#关于对象的配置
person:
  name: yaojikai
  age: 18
  addr: beijing
#行内对象配置
#person: {name: yaojikai,age: 18,addr: beijing}

server:
  port: 8082

#配置数据、集合(普通字符串)
city:
  - beijing
  - shanghai
  - tianjin
#行内对象配置
#city: [beijing,tianjin,shanghai]

student:
  - name: yaojikai
    age: 18
    addr: beijing
  - name: shimengyu
    age: 15
    addr: beijing
#行内对象配置
#student: [{name: yaojikai,age: 18,addr: beijing}, {name: shimengyu,age: 15,addr: beijing}]
