server:
  port: 8081
#  servlet:
#    context-path: /crud



spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  profiles:
    active: dev
  messages:
    basename: i18n.login
  thymeleaf:
    #禁用缓存
    cache: false

