spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    servlet:
      content-type: text/html
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jikaigg?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        dialect: com.jikaigg.shiro.config.MySQLConfig
        hbm2ddl:
          auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect