server:
  port: 10010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
zuul:
  routes:
    user-service: /user/**  #将来访问user-service用的连接为http://localhost:10010/user/user/{id}
  #    consumer-server: /consumer/**
  # com.netflix.zuul.exception.zuulexception timeout 超时报错
  host:
    connect-timeout-millis: 10000
    socket-timeout-millis: 60000
  #忽略某些服务，对外不暴露这些服务
  ignored-services:
    - consumer-server

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
spring:
  application:
    name: gateway