server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jikaigg
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.jikaigg.user.pojo
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
